var gulp         = require('gulp');
var rename       = require('gulp-rename');
var swig         = require('gulp-swig');
var config       = require('../../config/icons');
var handleErrors = require('../../lib/handleErrors');

module.exports = function (codepoints) {
    gulp.src(config.template)
        .pipe(swig({
            data: {
                icons: codepoints.map(function(icon) {
                    return {
                        name: icon.name,
                        code: icon.codepoint.toString(16)
                    }
                }),
                fontName: config.options.fontName,
                fontPath: config.fontPath,
                className: config.className,
                comment: 'Generated by gulp/task/icons.js -- DO NOT EDIT DIRECTLY!'
            }
        }))
        .on('error', handleErrors)
        .pipe(rename(config.sassOutputName))
        .pipe(gulp.dest(config.sassDest));
};
